"""CHMI adapter: calibration, projection, palette discipline, run discovery.

Driven by **recorded** fixtures: `tests/fixtures/chmi/observed.png` and
`forecast.tar` are real bytes from opendata.chmi.cz, regenerated by
`scripts/make_chmi_fixtures.py`. The expected mm/h values below are pinned to that
recorded run, so re-recording means recomputing them.

The two synthesized frames carry the same 680x460 geometry and exist to prove
negatives a recorded frame cannot: no echo anywhere, and echo somewhere else.
"""

from __future__ import annotations

import io
import math
import tarfile
from datetime import UTC, datetime, timedelta

import numpy as np
import pytest
from homeassistant.core import HomeAssistant
from homeassistant.helpers.aiohttp_client import async_get_clientsession
from PIL import Image
from pytest_homeassistant_custom_component.test_util.aiohttp import AiohttpClientMocker

from custom_components.walk_the_dog.cache import SampleCache
from custom_components.walk_the_dog.const import (
    INTENSITY_NONE,
    INTENSITY_THRESHOLD_HEAVY,
    INTENSITY_THRESHOLD_LIGHT,
    INTENSITY_THRESHOLD_MODERATE,
    SOURCE_CHMI,
    intensity_class,
)
from custom_components.walk_the_dog.sources.base import (
    RELIABILITY,
    STATE_FAILED,
    STATE_NOT_APPLICABLE,
    STATE_OK,
    SampleGeometry,
    dbz_to_mm_per_h,
)
from custom_components.walk_the_dog.sources.chmi import (
    DATA_EAST_LON,
    DATA_NORTH_LAT,
    DATA_SOUTH_LAT,
    DATA_WEST_LON,
    DOMAIN_OUTLINE_RGB,
    FORECAST_FRAMES,
    FRAME_HEIGHT,
    FRAME_WIDTH,
    IMAGE_EAST_LON,
    IMAGE_NORTH_LAT,
    IMAGE_SOUTH_LAT,
    IMAGE_WEST_LON,
    MAX_REQUESTS_PER_HOUR,
    MIN_INTERVAL_S,
    PALETTE_RGB,
    RANGE_FULL_KM,
    RANGE_LIMIT_KM,
    RANGE_MIN_FACTOR,
    ChmiAdapter,
    covers,
    covers_geometry,
    forecast_url,
    frame_window,
    level_to_mm_per_h,
    nearest_radar_km,
    observed_url,
    range_factor,
    reliability_at,
    run_candidates,
    to_pixel,
)
from custom_components.walk_the_dog.sources.chmi import _levels as classify_levels

from .conftest import CHMI_GEOMETRY, TEST_GEOMETRY, load_bytes

UA = "walk_the_dog/test (+https://github.com/zyndata/walk-the-dog)"

#: The run the recorded fixtures came from.
RUN = datetime(2026, 8, 26, 7, 50, tzinfo=UTC)

#: Bielsko-Biala, the disc the recorded frames were sampled over.
_BIELSKO = (49.8224, 19.0584)

#: What the recorded frames say over the Bielsko-Biala disc. Level 3 is 12 dBZ and
#: level 2 is 8 dBZ; both are light drizzle, which is what the composite showed.
OBSERVED_MM_H = 0.205048
FORECAST_MM_H = [0.205048, 0.205048, 0.205048, 0.115307, 0.115307, 0.115307]


# --- Calibration ------------------------------------------------------------------
#
# Verified live against CHMI's own legend, not assumed:
# https://opendata.chmi.cz/meteorology/weather/radar/scl/scl-dbz-mmh.png prints
# 4, 8, 12 ... 60 dBZ beside the 15 colours, and its mm/h gridlines for 0.1, 1, 10
# and 100 sit at 7, 23, 39 and 55 dBZ -- exactly where Z = 200 R^1.6 puts them.

CALIBRATION: list[tuple[int, int, float, str]] = [
    # level, dBZ, mm/h, class on the common scale
    (0, 0, 0.0, INTENSITY_NONE),  # transparent: no echo or no data
    (1, 4, 0.064842, INTENSITY_NONE),  # below the 0.1 mm/h light boundary
    (2, 8, 0.115307, INTENSITY_THRESHOLD_LIGHT),
    (3, 12, 0.205048, INTENSITY_THRESHOLD_LIGHT),
    (5, 20, 0.648420, INTENSITY_THRESHOLD_LIGHT),
    (7, 28, 2.050483, INTENSITY_THRESHOLD_LIGHT),  # just under 2.5 mm/h
    (8, 32, 3.646332, INTENSITY_THRESHOLD_MODERATE),  # just over it
    (9, 36, 6.484198, INTENSITY_THRESHOLD_MODERATE),  # just under 7.6 mm/h
    (10, 40, 11.530715, INTENSITY_THRESHOLD_HEAVY),  # just over it
    (13, 52, 64.841978, INTENSITY_THRESHOLD_HEAVY),
    (15, 60, 205.048338, INTENSITY_THRESHOLD_HEAVY),  # the top of the ramp
]


@pytest.mark.parametrize(("level", "dbz", "mm_per_h", "expected_class"), CALIBRATION)
def test_palette_level_calibration(
    level: int, dbz: int, mm_per_h: float, expected_class: str
) -> None:
    """Level -> 4*level dBZ -> Marshall-Palmer mm/h -> the common intensity class."""
    value = level_to_mm_per_h(level)

    assert level * 4 == dbz
    assert value == pytest.approx(mm_per_h, abs=1e-6)
    assert intensity_class(value) == expected_class


@pytest.mark.parametrize(
    ("mm_per_h", "dbz"), [(0.1, 7.0), (1.0, 23.0), (10.0, 39.0), (100.0, 55.0)]
)
def test_the_legend_decades_land_where_marshall_palmer_puts_them(
    mm_per_h: float, dbz: float
) -> None:
    """CHMI's mm/h gridlines pin the Z-R relation, and it is the project's own.

    This is the check that turned the calibration from an assumption into a fact.
    CHMI's legend draws 0.1, 1, 10 and 100 mm/h one whole dBZ below its 8, 24, 40 and
    56 labels — and `Z = 200 R^1.6` puts them at 7.01, 23.01, 39.01 and 55.01, i.e.
    inside a hundredth of a dBZ of exactly there. A different Z-R relation would miss
    by whole steps, so the tolerance below is far tighter than the thing it rules out.
    """
    assert dbz_to_mm_per_h(dbz) == pytest.approx(mm_per_h, rel=5e-3)


def test_level_zero_is_no_rain_not_missing_data() -> None:
    """Index 0 is fully transparent and means no echo — the same rule as LibreWXR grey 0."""
    assert level_to_mm_per_h(0) == 0.0


def test_levels_are_monotonic_and_clamped() -> None:
    """A higher palette index never means less rain, and nothing extrapolates past 15."""
    values = [level_to_mm_per_h(level) for level in range(16)]

    assert values == sorted(values)
    assert level_to_mm_per_h(99) == level_to_mm_per_h(15)


def test_the_palette_is_the_published_fifteen_step_ramp() -> None:
    """16 entries: transparent plus 15 echo levels, all distinct."""
    assert len(PALETTE_RGB) == 16
    assert len(set(PALETTE_RGB)) == 16
    assert PALETTE_RGB[0] == (0, 0, 0)
    assert PALETTE_RGB[15] == (0xFC, 0xFC, 0xFC)


# --- Range weighting --------------------------------------------------------------
#
# The composite's grid is a rectangle; the radars' sight is not. A beam climbs and
# widens with range, so the far corners of the domain are measured from above the
# weather. These tests pin the consequence: `chmi` is the one source whose consensus
# weight depends on where the user lives.


@pytest.mark.parametrize(
    ("name", "latitude", "longitude", "expected_km"),
    [
        ("Brno", 49.1951, 16.6068, 37),
        ("Praha", 50.0755, 14.4378, 64),
        ("Ostrava", 49.8209, 18.2625, 112),
        ("Bielsko-Biala", 49.8224, 19.0584, 167),
    ],
)
def test_distance_to_the_nearest_czrad_radar(
    name: str, latitude: float, longitude: float, expected_km: int
) -> None:
    """Skalky (49.501 N, 16.790 E) and Brdy-Praha (49.658 N, 13.818 E), per chmi.cz."""
    assert nearest_radar_km(latitude, longitude) == pytest.approx(expected_km, abs=2), name


def test_close_in_locations_keep_the_full_weight() -> None:
    """Inside 120 km the beam is still under ~2.7 km — nothing to discount."""
    assert range_factor(49.1951, 16.6068) == 1.0  # Brno, 37 km
    assert range_factor(49.8209, 18.2625) == 1.0  # Ostrava, 112 km


def test_the_weight_decays_beyond_the_full_range_and_then_floors() -> None:
    """Linear from 1.0 at `RANGE_FULL_KM` to `RANGE_MIN_FACTOR` at `RANGE_LIMIT_KM`."""
    midpoint = (RANGE_FULL_KM + RANGE_LIMIT_KM) / 2
    factors = [
        range_factor(*_at_range_from_skalky(km))
        for km in (RANGE_FULL_KM, midpoint, RANGE_LIMIT_KM, RANGE_LIMIT_KM + 50)
    ]

    assert factors[0] == pytest.approx(1.0, abs=0.02)
    assert factors[1] == pytest.approx((1.0 + RANGE_MIN_FACTOR) / 2, abs=0.02)
    assert factors[2] == pytest.approx(RANGE_MIN_FACTOR, abs=0.02)
    assert factors[3] == RANGE_MIN_FACTOR  # floored, never zero


def _at_range_from_skalky(km: float) -> tuple[float, float]:
    """A point due east of Skalky at roughly `km` — enough to exercise the curve."""
    skalky_lat, skalky_lon = 49.501, 16.790
    deg = km / (111.320 * math.cos(math.radians(skalky_lat)))
    return skalky_lat, skalky_lon + deg


def test_bielsko_biala_is_weighted_down_but_still_votes() -> None:
    """The case this was built for, stated as a number.

    Bielsko-Biala is 167 km from Skalky, where the 0.5 deg beam centre is ~3.9 km up,
    while the Polish radar feeding OPERA stands 44 km away and looks at ~0.85 km. So
    `chmi` must weigh less than `librewxr` there by a clear margin — enough that when
    the two disagree about rain, the better-sighted one wins the slot.
    """
    weight = reliability_at(*_BIELSKO)

    assert weight == pytest.approx(0.67, abs=0.02)
    assert weight < RELIABILITY[SOURCE_CHMI]
    assert weight < RELIABILITY["librewxr"]
    # The decisive property: librewxr voting wet outweighs chmi voting dry.
    assert RELIABILITY["librewxr"] / (RELIABILITY["librewxr"] + weight) > 0.5


def test_the_weight_never_exceeds_the_static_one() -> None:
    """The range factor only ever discounts; it cannot promote the source."""
    for latitude, longitude in (
        _BIELSKO,
        (49.501, 16.790),  # standing on Skalky itself
        (49.1951, 16.6068),
        (48.35, 19.32),  # the far south-eastern corner of the box
    ):
        assert reliability_at(latitude, longitude) <= RELIABILITY[SOURCE_CHMI]
        assert reliability_at(latitude, longitude) > 0.0


async def test_the_series_carries_the_range_adjusted_weight(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """The adapter must put the location's weight on the series, not the static one."""
    _mock_run(aioclient_mock)
    adapter = ChmiAdapter(UA)

    result = await adapter.fetch(async_get_clientsession(hass), chmi_geometry, at_run)

    assert result.series[0].reliability == pytest.approx(reliability_at(*_BIELSKO), abs=1e-9)
    assert result.series[0].reliability < RELIABILITY[SOURCE_CHMI]
    assert "km from the nearest CHMI radar" in (result.statuses[0].detail or "")


# --- Coverage gating --------------------------------------------------------------


@pytest.mark.parametrize(
    ("name", "latitude", "longitude", "inside"),
    [
        ("Bielsko-Biala", 49.8224, 19.0584, True),
        ("Praha", 50.0755, 14.4378, True),
        ("Ostrava", 49.8209, 18.2625, True),
        # East of 19.624 E, where the composite's data simply stops.
        ("Krakow", 50.0647, 19.9450, False),
        # North of 51.458 N.
        ("Warszawa", 52.2297, 21.0122, False),
        ("Gdansk", 54.3520, 18.6466, False),
        # Inside the raw data rectangle but within the inset margin, so still refused.
        ("just inside the eastern edge", 49.8000, DATA_EAST_LON - 0.1, False),
        ("just inside the northern edge", DATA_NORTH_LAT - 0.1, 15.0, False),
        ("just inside the southern edge", DATA_SOUTH_LAT + 0.1, 15.0, False),
        ("just inside the western edge", 49.8000, DATA_WEST_LON + 0.1, False),
    ],
)
def test_coverage_box(name: str, latitude: float, longitude: float, inside: bool) -> None:
    """The composite reaches south-western Poland and stops well short of the rest."""
    assert covers(latitude, longitude) is inside, name


def test_the_whole_disc_must_be_covered_not_just_its_centre() -> None:
    """Outside the data rectangle every pixel is transparent, i.e. reads as no echo."""
    edge = SampleGeometry(latitude=49.8, longitude=DATA_EAST_LON - 0.31, radius_km=15.0)

    assert covers(edge.latitude, edge.longitude) is True
    assert covers_geometry(edge) is False


def test_bielsko_biala_is_covered_and_warszawa_is_not() -> None:
    """The behaviour the source was added for, stated as a test."""
    assert covers_geometry(CHMI_GEOMETRY) is True
    assert covers_geometry(TEST_GEOMETRY) is False


async def test_an_uncovered_location_is_never_fetched(
    hass: HomeAssistant, aioclient_mock: AiohttpClientMocker, now: datetime
) -> None:
    """Outside the box the adapter reports `not_applicable` and makes no request."""
    adapter = ChmiAdapter(UA)

    result = await adapter.fetch(async_get_clientsession(hass), TEST_GEOMETRY, now)

    assert aioclient_mock.call_count == 0
    assert [(s.source_id, s.state, s.contributed) for s in result.statuses] == [
        (SOURCE_CHMI, STATE_NOT_APPLICABLE, False)
    ]
    assert result.series == ()


# --- Projection -------------------------------------------------------------------


def test_the_published_extent_describes_a_web_mercator_frame() -> None:
    """Longitude and Mercator northing must share one scale, or it is not EPSG:3857.

    Deriving `px per radian of longitude` and `px per Mercator unit` from CHMI's
    published image extent and the real 680x460 frame gives the same number to
    0.02 %. No other projection would come out consistent.
    """
    px_per_lon_radian = FRAME_WIDTH / math.radians(IMAGE_EAST_LON - IMAGE_WEST_LON)
    merc_span = math.asinh(math.tan(math.radians(IMAGE_NORTH_LAT))) - math.asinh(
        math.tan(math.radians(IMAGE_SOUTH_LAT))
    )
    px_per_merc_unit = FRAME_HEIGHT / merc_span

    assert px_per_lon_radian == pytest.approx(px_per_merc_unit, rel=1e-3)


def test_the_data_rectangle_lands_where_chmi_says_it_does() -> None:
    """The data extent maps to (0, 82)-(598, 460) inside the 680x460 image.

    This is the independent check on the whole geometry: CHMI publishes the image
    extent and the data extent separately, and the second falls on whole-pixel
    boundaries only if the first is being applied correctly.
    """
    x0, y0 = to_pixel(DATA_NORTH_LAT, DATA_WEST_LON)
    x1, y1 = to_pixel(DATA_SOUTH_LAT, DATA_EAST_LON)

    assert (x0, y1) == pytest.approx((0.0, FRAME_HEIGHT), abs=0.1)
    assert y0 == pytest.approx(82.0, abs=0.1)
    assert x1 == pytest.approx(598.0, abs=0.1)


def test_one_pixel_is_about_one_kilometre() -> None:
    """CHMI states 1x1 km; the frame's own extent has to agree."""
    mid_lat = (DATA_NORTH_LAT + DATA_SOUTH_LAT) / 2
    km_per_deg_lon = 111.320 * math.cos(math.radians(mid_lat))
    km_per_px = km_per_deg_lon * (IMAGE_EAST_LON - IMAGE_WEST_LON) / FRAME_WIDTH

    assert km_per_px == pytest.approx(1.0, abs=0.02)


def test_the_frame_window_lands_on_bielsko_biala() -> None:
    """~557, 267 in frame pixels — inside the data rectangle, near its eastern edge."""
    window = frame_window(CHMI_GEOMETRY)

    assert window.x0 <= 557 <= window.x1
    assert window.y0 <= 267 <= window.y1
    assert window.box == (window.x0, window.y0, window.x1, window.y1)


def test_a_five_kilometre_disc_is_about_ten_pixels_across() -> None:
    """~1 km per pixel: the disc is small, which is why only it is decoded."""
    window = frame_window(CHMI_GEOMETRY)

    assert 8 <= window.x1 - window.x0 <= 14
    assert 8 <= window.y1 - window.y0 <= 14
    assert 60 <= int(window.mask.sum()) <= 100


# --- URLs and run discovery -------------------------------------------------------


def test_observed_url() -> None:
    """The MAX_Z composite for a run."""
    assert observed_url(RUN) == (
        "https://opendata.chmi.cz/meteorology/weather/radar/composite/"
        "maxz/png/pacz2gmaps3.z_max3d.20260826.0750.0.png"
    )


def test_forecast_url_is_one_archive_for_the_whole_run() -> None:
    """`ft60s10` — forecast to 60 minutes, step 10. Six frames, one request."""
    assert forecast_url(RUN) == (
        "https://opendata.chmi.cz/meteorology/weather/radar/composite/"
        "fct_maxz/png/pacz2gmaps3.fct_z_max.20260826.0750.ft60s10.tar"
    )


def test_run_candidates_walk_the_five_minute_grid_backwards() -> None:
    """There is no feed to ask, so run times are computed, newest first."""
    candidates = run_candidates(datetime(2026, 8, 26, 8, 0, 30, tzinfo=UTC))

    assert candidates == [
        datetime(2026, 8, 26, 7, 55, tzinfo=UTC),
        datetime(2026, 8, 26, 7, 50, tzinfo=UTC),
        datetime(2026, 8, 26, 7, 45, tzinfo=UTC),
    ]


def test_run_candidates_allow_for_publication_lag() -> None:
    """A run is named for the end of its interval and appears a moment later.

    Right after 08:00 the 08:00 run is usually not there yet, so asking for it would
    just spend a request on a 404.
    """
    assert run_candidates(datetime(2026, 8, 26, 8, 0, 10, tzinfo=UTC))[0] == datetime(
        2026, 8, 26, 7, 55, tzinfo=UTC
    )


# --- Fetching and sampling --------------------------------------------------------


def _mock_run(
    aioclient_mock: AiohttpClientMocker,
    *,
    run: datetime = RUN,
    observed: str | None = "observed.png",
    forecast: str | None = "forecast.tar",
) -> None:
    """Serve one run from the recorded fixtures."""
    if forecast is not None:
        aioclient_mock.get(forecast_url(run), content=load_bytes("chmi", forecast))
    if observed is not None:
        aioclient_mock.get(observed_url(run), content=load_bytes("chmi", observed))


@pytest.fixture
def at_run() -> datetime:
    """A clock for which `RUN` is the newest published run."""
    return RUN + timedelta(minutes=3)


async def test_fetch_builds_a_contiguous_ten_minute_series(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """Observation plus six forecast frames: the run time and +10…+60 after it."""
    _mock_run(aioclient_mock)
    adapter = ChmiAdapter(UA)

    result = await adapter.fetch(async_get_clientsession(hass), chmi_geometry, at_run)

    series = result.series[0]
    assert series.source_id == SOURCE_CHMI
    assert series.step_s == 600
    assert series.issued_at == RUN
    assert series.fetched_at == at_run
    starts = [slot for slot, _ in series.slots]
    assert starts == [RUN + timedelta(minutes=10 * k) for k in range(7)]
    assert series.horizon_end == RUN + timedelta(minutes=70)


async def test_one_cycle_costs_two_requests(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """The whole forecast arrives in one archive — that is why this source is cheap."""
    _mock_run(aioclient_mock)
    adapter = ChmiAdapter(UA)

    result = await adapter.fetch(async_get_clientsession(hass), chmi_geometry, at_run)

    assert len(result.series[0].slots) == FORECAST_FRAMES + 1
    assert aioclient_mock.call_count == 2


async def test_the_recorded_run_reads_back_exactly(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """Pinned to the real bytes: light drizzle over Bielsko-Biala, easing over the hour.

    These are the numbers the live comparison produced, and the same disc sampled
    from LibreWXR's OPERA composite at the same moment read 12 dBZ too.
    """
    _mock_run(aioclient_mock)
    adapter = ChmiAdapter(UA)

    result = await adapter.fetch(async_get_clientsession(hass), chmi_geometry, at_run)

    values = [value for _, value in result.series[0].slots]
    assert values[0] == pytest.approx(OBSERVED_MM_H, abs=1e-6)
    assert values[1:] == pytest.approx(FORECAST_MM_H, abs=1e-6)
    assert all(intensity_class(value) == INTENSITY_THRESHOLD_LIGHT for value in values)


async def test_a_transparent_frame_is_dry_not_missing(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """No echo must produce zeroes, not a gap — "dry" and "unknown" are different."""
    _mock_run(aioclient_mock, observed="frame_dry.png")
    adapter = ChmiAdapter(UA)

    result = await adapter.fetch(async_get_clientsession(hass), chmi_geometry, at_run)

    assert result.series[0].slots[0][1] == 0.0
    assert result.statuses[0].state == STATE_OK


async def test_rain_somewhere_else_in_the_domain_does_not_count(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """The projection has to be right, not merely plausible.

    `frame_elsewhere.png` puts a heavy echo over Praha and nothing anywhere else. A
    disc sampled at Bielsko-Biala must read dry; a projection off by even a few tens
    of pixels would pick the storm up.
    """
    _mock_run(aioclient_mock, observed="frame_elsewhere.png")
    adapter = ChmiAdapter(UA)

    result = await adapter.fetch(async_get_clientsession(hass), chmi_geometry, at_run)

    assert result.series[0].slots[0][1] == 0.0


async def test_a_missing_observed_frame_still_leaves_a_usable_forecast(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """The +10…+60 nowcast is the valuable part; losing "now" is not worth failing over."""
    _mock_run(aioclient_mock, observed=None)
    aioclient_mock.get(observed_url(RUN), status=404)
    adapter = ChmiAdapter(UA)

    result = await adapter.fetch(async_get_clientsession(hass), chmi_geometry, at_run)

    series = result.series[0]
    assert len(series.slots) == FORECAST_FRAMES
    assert series.slots[0][0] == RUN + timedelta(minutes=10)
    assert result.statuses[0].state == STATE_OK


async def test_an_unpublished_run_falls_back_to_the_previous_one(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
) -> None:
    """A late run costs one 404 and the cycle carries on with the run before it."""
    later = RUN + timedelta(minutes=5)
    aioclient_mock.get(forecast_url(later), status=404)
    _mock_run(aioclient_mock)
    adapter = ChmiAdapter(UA)

    result = await adapter.fetch(
        async_get_clientsession(hass), chmi_geometry, later + timedelta(minutes=3)
    )

    assert result.series[0].issued_at == RUN
    assert result.statuses[0].state == STATE_OK


# --- Palette discipline -----------------------------------------------------------


def _blended_frame() -> bytes:
    """A frame rendered the way CHMI's `png_masked` variants are: echo blended.

    This is the exact failure the live check turned up — #B1B1D0 over Bielsko-Biala,
    whose nearest palette neighbour is the white top of the ramp.
    """
    image = Image.new("RGB", (FRAME_WIDTH, FRAME_HEIGHT), (0xB1, 0xB1, 0xD0))
    buffer = io.BytesIO()
    image.save(buffer, format="PNG")
    return buffer.getvalue()


async def test_off_palette_pixels_are_refused_not_guessed(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """A blended frame must fail loudly rather than read as the top of the ramp.

    Nearest-colour matching would resolve #B1B1D0 to #FCFCFC and report 205 mm/h for
    light drizzle. Producing confident nonsense is the one failure this project
    cannot have, so an unrecognised colour is "no data" and a disc full of them is
    an error.
    """
    aioclient_mock.get(forecast_url(RUN), content=_blended_frame())
    adapter = ChmiAdapter(UA)

    result = await adapter.fetch(async_get_clientsession(hass), chmi_geometry, at_run)

    assert result.series == ()
    assert result.statuses[0].state == STATE_FAILED


def test_the_domain_outline_is_not_precipitation() -> None:
    """#C4C4C4 outlines the data area. Nearest-colour would call it extreme hail."""
    patch = np.zeros((1, 2, 4), dtype=np.uint8)
    patch[0, 0, :3] = DOMAIN_OUTLINE_RGB
    patch[0, 1, :3] = PALETTE_RGB[3]
    patch[..., 3] = 255

    levels = classify_levels(patch)

    assert levels[0, 0] == -1  # excluded from the sample
    assert levels[0, 1] == 3


def test_the_recorded_frame_is_entirely_on_the_published_palette() -> None:
    """Every opaque pixel of a real frame is an exact palette colour or the outline.

    If CHMI ever changes how these are rendered, this is the test that says so
    instead of the readings quietly drifting.
    """
    with Image.open(io.BytesIO(load_bytes("chmi", "observed.png"))) as image:
        rgba = np.asarray(image.convert("RGBA"))

    known = {*PALETTE_RGB, DOMAIN_OUTLINE_RGB}
    opaque = rgba[rgba[..., 3] > 0][:, :3]
    unknown = {tuple(px) for px in opaque.tolist()} - known

    assert not unknown, f"unrecognised colours in a real frame: {sorted(unknown)}"


def test_the_recorded_forecast_archive_holds_six_ten_minute_frames() -> None:
    """`ft60s10` on the tin, and the same on the inside."""
    with tarfile.open(fileobj=io.BytesIO(load_bytes("chmi", "forecast.tar"))) as archive:
        frames = [m for m in archive.getmembers() if m.isfile() and m.name.endswith(".png")]
        sizes = set()
        for member in frames:
            payload = archive.extractfile(member)
            assert payload is not None
            with Image.open(io.BytesIO(payload.read())) as image:
                sizes.add((image.width, image.height))

    assert len(frames) == FORECAST_FRAMES
    assert sizes == {(FRAME_WIDTH, FRAME_HEIGHT)}


# --- Politeness, caching, failure -------------------------------------------------


async def test_requests_identify_this_project(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """An honest `User-Agent` on every request, and no other identifying header."""
    _mock_run(aioclient_mock)
    adapter = ChmiAdapter(UA)

    await adapter.fetch(async_get_clientsession(hass), chmi_geometry, at_run)

    for _method, _url, _data, headers in aioclient_mock.mock_calls:
        assert headers["User-Agent"] == UA


async def test_requests_go_over_https(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """The reason this source is CHMI's own endpoint and not the app's mirror."""
    _mock_run(aioclient_mock)
    adapter = ChmiAdapter(UA)

    await adapter.fetch(async_get_clientsession(hass), chmi_geometry, at_run)

    assert aioclient_mock.mock_calls
    for _method, url, _data, _headers in aioclient_mock.mock_calls:
        assert str(url).startswith("https://")


async def test_a_cached_observed_frame_is_not_fetched_twice(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """Frames are immutable once published, so re-reading a run costs one request."""
    _mock_run(aioclient_mock)
    cache = SampleCache(chmi_geometry.key)
    adapter = ChmiAdapter(UA, cache=cache)

    session = async_get_clientsession(hass)
    await adapter.fetch(session, chmi_geometry, at_run)
    first_pass = aioclient_mock.call_count
    await adapter.fetch(session, chmi_geometry, at_run)

    assert first_pass == 2
    # Only the forecast archive: the observed frame was already sampled.
    assert aioclient_mock.call_count == first_pass + 1


async def test_the_hourly_budget_is_never_exceeded(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
) -> None:
    """A stuck cycle loop must not turn into unbounded traffic on someone else's host."""
    adapter = ChmiAdapter(UA)
    session = async_get_clientsession(hass)

    for minute in range(0, 120, 10):
        moment = RUN + timedelta(minutes=3 + minute)
        aioclient_mock.clear_requests()
        for candidate in run_candidates(moment):
            _mock_run(aioclient_mock, run=candidate)
        await adapter.fetch(session, chmi_geometry, moment)
        assert adapter._budget.remaining(moment) >= 0

    assert adapter._budget.limit == MAX_REQUESTS_PER_HOUR


async def test_a_failed_provider_does_not_break_the_cycle(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """Every candidate run 404s: one silent source, not a broken update."""
    for candidate in run_candidates(at_run):
        aioclient_mock.get(forecast_url(candidate), status=404)
    adapter = ChmiAdapter(UA)

    result = await adapter.fetch(async_get_clientsession(hass), chmi_geometry, at_run)

    assert result.series == ()
    assert result.statuses[0].state == STATE_FAILED
    assert result.ok is False


async def test_a_failure_reuses_the_previous_frames_while_they_are_fresh(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """One bad cycle should not blind the source; a stale one still must."""
    _mock_run(aioclient_mock)
    adapter = ChmiAdapter(UA)
    session = async_get_clientsession(hass)
    await adapter.fetch(session, chmi_geometry, at_run)

    aioclient_mock.clear_requests()
    soon = at_run + timedelta(minutes=10)
    later = at_run + timedelta(hours=3)
    for moment in (soon, later):
        for candidate in run_candidates(moment):
            aioclient_mock.get(forecast_url(candidate), status=500)

    soon_result = await adapter.fetch(session, chmi_geometry, soon)
    later_result = await adapter.fetch(session, chmi_geometry, later)

    assert soon_result.statuses[0].state == STATE_OK
    assert soon_result.series
    assert later_result.statuses[0].state == STATE_FAILED


async def test_a_frame_of_the_wrong_size_is_refused(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """The geometry is the whole basis of the reading; a different frame is not it."""
    aioclient_mock.get(forecast_url(RUN), content=load_bytes("librewxr", "tile_wet.png"))
    adapter = ChmiAdapter(UA)

    result = await adapter.fetch(async_get_clientsession(hass), chmi_geometry, at_run)

    assert result.statuses[0].state == STATE_FAILED


async def test_a_published_run_is_fetched_once_however_often_the_cycle_runs(
    hass: HomeAssistant,
    aioclient_mock: AiohttpClientMocker,
    chmi_geometry: SampleGeometry,
    at_run: datetime,
) -> None:
    """CHMI publishes every five minutes; the coordinator may wake more often than that.

    It sprints to five minutes near a walk and wakes again whenever a frame is due,
    so the cadence has to be the source's own rather than the cycle's.
    """
    _mock_run(aioclient_mock)
    adapter = ChmiAdapter(UA)

    assert adapter.should_fetch(at_run)
    await adapter.fetch(async_get_clientsession(hass), chmi_geometry, at_run)

    assert not adapter.should_fetch(at_run + timedelta(seconds=MIN_INTERVAL_S // 2))
    assert adapter.should_fetch(at_run + timedelta(seconds=MIN_INTERVAL_S))
